guests = ["Umar Muxtor", "Sheyx Muhammad Sodiq", "Adolf Hitler"]
guests.insert(0, "Toriq ibn Ziyod")
guests.insert(2, "Yorqinjon domla")
guests.append("Yusuf Hajjoj")
print(guests)
print(f"I invite {guests[0]} to the dinner")
print(f"I invite {guests[1]} to the dinner")
print(f"I invite {guests[2]} to the dinner")
print(f"I invite {guests[3]} to the dinner")
print(f"I invite {guests[4]} to the dinner")
print(f"I invite {guests[5]} to the dinner")